services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6380:6379
    volumes:
      - redis_cache:/data
  postgres:
      restart: always
      container_name: postgres
      image: postgis/postgis:15-3.3
      environment:
          POSTGRES_USER: '${POSTGRES_USER}'
          POSTGRES_DB: '${POSTGRES_DATABASE}'
          POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      ports:
          - 5432:5432
      volumes:
          - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: app
    depends_on:
      - redis
      - postgres
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  caddy_data:
  caddy_config:
  postgres_data:
  redis_cache:
    driver: local
